name: my_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # Menambahkan font Cupertino Icons ke aplikasi Anda.
  # Gunakan dengan kelas CupertinoIcons untuk ikon gaya iOS.
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_analytics: ^10.10.7
  delightful_toast: ^1.1.0
  get_it: ^7.7.0
  image_picker: ^1.1.2
  path: ^1.9.0
  intl: ^0.19.0
  intl_utils: ^2.8.7
  dash_chat_2: ^0.0.20
  shared_preferences: ^2.0.15
  bloc: ^8.1.4
  cached_network_image: ^3.3.1
  cloud_firestore: ^4.17.3
  file_picker: ^8.0.3
  firebase_auth: ^4.19.5
  firebase_core: ^2.31.0
  firebase_storage: ^11.7.5
  freezed_annotation: ^2.4.1
  google_fonts: ^6.2.1
  isar: ^3.1.0+1
  json_annotation: ^4.9.0
  permission_handler: ^11.3.1
  uuid: ^4.4.0
  flutter_svg: ^1.0.3
  flutter_background: ^1.2.0
  flutter_local_notifications: ^17.1.2
  awesome_notifications: ^0.9.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.10
  freezed: ^2.5.2
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/LanguageOnboarding.png
    - assets/indonesia.png
    - assets/english.png
    - assets/ProfileIcon.png
    - assets/ChatDokter.png
    - assets/TokoKesehatan.png
    - assets/HomeLabVaksinasi.png
    - assets/Asuransiku.png
    - assets/KesehatanMental.png
    - assets/Haloskin.png
    - assets/BuatJanjiOffline.png
    - assets/LihatSemua.png
    - assets/Promo1.png
    - assets/Promo2.png
    - assets/Promo3.png
    - assets/StethoscopeIcon.png
    - assets/Article1.png
    - assets/IconCS.png
    - assets/englishhh.png
    - assets/vector.png
    - assets/arrowback.png
    - assets/indonesia.svg
    - assets/english.svg
    - assets/female.svg
    - assets/male.svg
    - assets/doctor_image.jpg
    - assets/pediatrician2.png
    - assets/dentist2.png
    - assets/pulmonologist2.png
    - assets/surgeon2.png
    - assets/neurologist2.png
    - assets/online.svg
    - assets/offline.svg
    - assets/gradu.png
    - assets/practice.png
    - assets/calendar.png
    - assets/arrowback copy.png
    - assets/pediatrician.svg
    - assets/dentist.svg
    - assets/pulmonologist.svg
    - assets/surgeon.svg
    - assets/neurologist.svg
    - assets/indonesia.svg
    - assets/english.svg
    - assets/female copy.svg
    - assets/male.svg
    - assets/doctor_image.svg
    - assets/doctor_image.png
    - assets/pediatrician2.png
    - assets/dentist2 copy.png
    - assets/pulmonologist2.png
    - assets/surgeon2 copy.png
    - assets/neurologist2 copy.png
    - assets/online copy.svg
    - assets/offline copy.svg
    - assets/calendar.png
    - assets/pedi.png
    - assets/denti.png
    - assets/pulmo.png
    - assets/neuro.png
    - assets/surge.png
    - assets/gradu.png
    - assets/neurologist.svg
    - assets/thumbs-up.svg
    - assets/dentist.svg
    # - assets/age.png
    # - assets/practice copy.png

  fonts: 
  - family: Nunito
    fonts: 
    - asset: assets/fonts/Nunito-Bold.ttf
      weight: 700
    - asset: assets/fonts/Nunito-Medium.ttf
      weight: 500
    - asset: assets/fonts/Nunito-Regular.ttf
      weight: 400
    - asset: assets/fonts/Nunito-SemiBold.ttf
      weight: 600

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
 

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
