name: rekmed
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_analytics: ^10.10.7
  delightful_toast: ^1.1.0
  get_it: ^7.7.0
  image_picker: ^1.1.2
  path: ^1.9.0
  intl: ^0.19.0
  dash_chat_2: ^0.0.20
  shared_preferences: ^2.0.15
  bloc: ^8.1.4
  cached_network_image: ^3.3.1
  cloud_firestore: ^4.17.3
  file_picker: ^8.0.3
  firebase_auth: ^4.19.5
  firebase_core: ^2.31.0
  firebase_storage: ^11.7.5
  freezed_annotation: ^2.4.1
  google_fonts: ^6.2.1
  isar: ^3.1.0+1
  json_annotation: ^4.9.0
  permission_handler: ^11.3.1
  uuid: ^4.4.0
  flutter_svg: ^1.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.10
  freezed: ^2.5.2
  json_serializable: ^6.8.0



flutter:
  uses-material-design: true
  assets:
    - assets/LanguageOnboarding.png
    - assets/indonesia.png
    - assets/english.png
    - assets/ProfileIcon.png
    - assets/ChatDokter.png
    - assets/TokoKesehatan.png
    - assets/HomeLabVaksinasi.png
    - assets/Asuransiku.png
    - assets/KesehatanMental.png
    - assets/Haloskin.png
    - assets/BuatJanjiOffline.png
    - assets/LihatSemua.png
    - assets/Promo1.png
    - assets/Promo2.png
    - assets/Promo3.png
    - assets/StethoscopeIcon.png
    - assets/Article1.png
    - assets/IconCS.png
    - assets/englishhh.png
    - assets/vector.png
    - assets/arrowback.png
    - assets/indonesia.svg
    - assets/english.svg
    - assets/female.svg
    - assets/male.svg
    - assets/doctor_image.png
    - assets/pediatrician2.png
    - assets/dentist2.png
    - assets/pulmonologist2.png
    - assets/surgeon2.png
    - assets/neurologist2.png
    - assets/online.svg
    - assets//offline.svg
    - assets/gradu.png
    - assets/practice.png
    - assets/calendar.png
    
  
  fonts: 
  - family: Nunito
    fonts: 
    - asset: assets/fonts/Nunito-Bold.ttf
      weight: 700
    - asset: assets/fonts/Nunito-Medium.ttf
      weight: 500
    - asset: assets/fonts/Nunito-Regular.ttf
      weight: 400
    - asset: assets/fonts/Nunito-SemiBold.ttf
      weight: 600

