// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBd5VGI3JOABB0y09bxROGjDWwdwXC1e9Y',
    appId: '1:474760710820:web:d885d70d1229128ffdf431',
    messagingSenderId: '474760710820',
    projectId: 'chating-2ed0b',
    authDomain: 'chating-2ed0b.firebaseapp.com',
    storageBucket: 'chating-2ed0b.appspot.com',
    measurementId: 'G-VTDBV494ZT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOtSBWM371PmfhpT4ng7gtBoGNjIX22w0',
    appId: '1:474760710820:android:04c8349311399e09fdf431',
    messagingSenderId: '474760710820',
    projectId: 'chating-2ed0b',
    storageBucket: 'chating-2ed0b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2fCsmmV0ZwcLcwmE9kSZHPXX4uMPjuik',
    appId: '1:474760710820:ios:c7fa6459cb9dbd23fdf431',
    messagingSenderId: '474760710820',
    projectId: 'chating-2ed0b',
    storageBucket: 'chating-2ed0b.appspot.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2fCsmmV0ZwcLcwmE9kSZHPXX4uMPjuik',
    appId: '1:474760710820:ios:c7fa6459cb9dbd23fdf431',
    messagingSenderId: '474760710820',
    projectId: 'chating-2ed0b',
    storageBucket: 'chating-2ed0b.appspot.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBd5VGI3JOABB0y09bxROGjDWwdwXC1e9Y',
    appId: '1:474760710820:web:2e9b07ddf8e4bdd5fdf431',
    messagingSenderId: '474760710820',
    projectId: 'chating-2ed0b',
    authDomain: 'chating-2ed0b.firebaseapp.com',
    storageBucket: 'chating-2ed0b.appspot.com',
    measurementId: 'G-2V2NJHREWG',
  );
}